### ISSUE TITLE
Problem with up-limiter=police on Ubuntu 20.04

### ISSUE THREAD

**Issue by slima** [accel-ppp/accel-ppp-docs#4]
Hi, 

accel-cmd 1.12.0-103-g45896ff on Ubuntu 20.04 5.4.0-51-generic

```
[shaper]
attr=Filter-Id
down-burst-factor=1.0
up-burst-factor=10.0
up-limiter=police
down-limiter=tbf
```
ipoe session has rate-limit: 10240/102400

Download speed at the client max: 3.15Mbit/s

When up-limiter=htb and ifb=ifb0 working as expected 97-99Mbit/s

PPPoE is not affected

**Comment by DmitriyEshenko** [comment]
Hi, try to disable offloads features on your NICs (tso gso gro)

**Comment by slima** [comment]
Hi, Yes, it helped.
Thanks a lot.
